# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
          python-version: 3.8
          
    - name: install depenciences
    - run: |
       pip install -r requirements.txt
       pip install black flake8
       
  - name: Run linters
    uses: wearerequired/lint-action@v2
    with:
        black: true
        flake8: true
       
    
 

 
